# Test file for TOML
# Only this one tries to emulate a TOML file written by a user of the kind of parser writers probably hate
# This part you'll really hate

[the]
test_string = "You'll hate me after this - #" # " Annoying, isn't it?

    [the.hard]
    test_array = [ "] ", " # "] # ] There you go, parse this!
    test_array2 = [ "Test #11 ]proved that", "Experiment #9 was a success" ]
    # You didn't think it'd as easy as chucking out the last #, did you?
    another_test_string = " Same thing, but with a string #"
    harder_test_string = " And when \"'s are in the string, along with # \"" # "and comments are there too"
    chinese_test_string = "\/白日依山盡，\\\n\/黃河入海流；\\\n\/欲窮千里目，\\\n\/更上一層樓。\\\n"
    # Things will get harder

        [the.hard.bit#]
        what? = "You don't think some user won't do that?"
        multi_line_array = [
            "]",
            # ] Oh yes I did
            ]
 
	
 	 	
    [the.hard.bool]
    true = true
        false = false
